### PR TITLE
Fixed unresolved reference in spec caused by #4

### PR DESCRIPTION
**Pull request by emmberk**
#### What does this PR do?
See https://github.com/connexta/ion-ingest-api/pull/4/files. The Swagger editor currently complains that there is a bad reference on line 108.

image

#### Who is reviewing it?
@ahoffer @jhunzik @lessarderic @paouelle @brendan-hofmann 

#### How should this be tested?
Verify that the API does not return 415.

### CODE REVIEW

**Comment by emmberk** [comment]
build now

**Comment by emmberk** [comment]
```
[2019-07-02T21:15:44.202Z] [ERROR] COMPILATION ERROR : 
14:15:44  [INFO] -------------------------------------------------------------
[2019-07-02T21:15:44.202Z] [ERROR] /jenkins/workspace/ION/ion-ingest-api/PR-16/1/rest/servers/spring/target/generated-sources/openapi/src/main/java/com/connexta/ingest/rest/spring/IngestApi.java:[9,39] cannot find symbol
14:15:44    symbol:   class UNKNOWN_BASE_TYPE
14:15:44    location: package com.connexta.ingest.rest.models
[2019-07-02T21:15:44.202Z] [ERROR] /jenkins/workspace/ION/ion-ingest-api/PR-16/1/rest/servers/spring/target/generated-sources/openapi/src/main/java/com/connexta/ingest/rest/spring/IngestApi.java:[51,386] cannot find symbol
14:15:44    symbol:   class UNKNOWN_BASE_TYPE
14:15:44    location: interface com.connexta.ingest.rest.spring.IngestApi
```

**Comment by emmberk** [comment]
build now

**Comment by emmberk** [comment]
build now

**Comment by emmberk** [comment]
not sure why the status check wasn't reported

build now

**Comment by jhunzik** [comment]
✅ Successful full build and verified that the docs render in the Swagger UI correctly.

**Comment by emmberk** [comment]
I overrode the CI build check. I'm not sure why it's not reporting back the check.
